# Netlify Configuration for TypeScript Documentation Build
# This project uses Swift/Kotlin for native mobile platforms,
# but documentation is built using TypeDoc (Node.js only)

[build]
  command = "yarn update-versions && yarn doc-gen"
  publish = "docs"

[build.environment]
  # Swift 6.0 is compatible with Ubuntu 24.04 (noble) build image
  # Package.swift triggers automatic swift build, so we need Swift installed
  SWIFT_VERSION = "6.0"
  

