name: 🐛 Bug Report
description: Report a reproducible bug or regression in Adapty Capacitor SDK.
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Please provide all the requested information. It will help us to resolve this issue faster
- type: textarea
  id: what-happened
  attributes:
    label: Description
    description: |
      Please provide a clear and concise description of what the bug is. Include screenshots and logs if needed
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: What version of `@adapty/capacitor` are you running?
    placeholder: v3.0.0
  validations:
    required: true
- type: dropdown
  id: platforms
  attributes:
    label: What platforms are you seeing the problem on?
    multiple: true
    options:
      - iOS
      - Android
  validations:
    required: true
- type: textarea
  id: capacitor-info
  attributes:
    label: Capacitor info
    description: |
      Run `npx cap doctor` in your terminal, copy and paste the results here.
    render: yml
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: |
      Please provide clear step-by-step instructions to reproduce the issue
    placeholder: |
      1. Call `await AdaptyCapacitor.activate(...)`
      2. Call `await AdaptyCapacitor.getPaywall(...)`
      3. See error
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen
    placeholder: |
      Expected the paywall to load successfully
  validations:
    required: true
- type: textarea
  id: actual-behavior
  attributes:
    label: Actual behavior
    description: |
      A clear and concise description of what actually happened
    placeholder: |
      Got an error: "Failed to load paywall"
  validations:
    required: true
- type: textarea
  id: reproduction-code
  attributes:
    label: Minimal reproduction code
    description: |
      Please provide a minimal code example that reproduces the issue
    placeholder: |
      ```typescript
      // Your minimal reproduction code here
      ```
    render: typescript
  validations:
    required: false
- type: textarea
  id: system-info
  attributes:
    label: Development environment
    description: |
      Please provide your development environment details
    placeholder: |
      - OS: macOS 15
      - Node.js: v20.17.0
      - Xcode: 26 (if iOS issue)
      - Android SDK: 35 (if Android issue)
      - Device/Simulator: Simulator iPhone 16 Pro (iOS 17.1)
    render: yml
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here (logs, screenshots, etc.)
    placeholder: |
      Add any relevant logs, screenshots, or additional information
  validations:
    required: false
